export const URL = 'http://192.168.1.199:8080/';
// export const URL = 'http://192.168.1.7:8080/';
// export const LOGIN = URL + '';
// export const REGISTER = URL +'';
// export const API_GETCATEGORY = URL + 'app-list-category';
// export const API_HOT_PRODUCTS = URL + 'app-list-hot-order-product';
// export const API_HOTSALE_PRODUCTS = URL +'app-list-sale-order-product';
// export const API_NEW_PRODUCTS = URL +'app-list-new-order-product';
// export const API_PRODUCT_CATEGORY = URL+'app-list-product-by-category';
// export const API_PRODUCTS = URL + '';
// export const API_CART = URL + '';
export const LOGIN = URL+"api/login-member"
export const ADDMENBER = URL+"api/add-member"
export const PROFILEMEMBER = URL+"api/profile-member"
export const EDITPROFILEMEMBER = URL+"api/edit-profile-member"
export const NAPTIENMEMBER = URL+"api/naptien-members"
export const LICHSUNAPTIENMEMBER = URL+"api/lich-su-naptien-members"
export const GETCATEGORIES = URL+"api/get-all-categories"
export const GETALLPRODUCTS = URL+"api/get-all-total-product"
export const GET_ONE_PRODUCT = URL+"api/get-one-product"
export const GETCARTUSER = URL+"api/user-carts-product"
export const POSTCARTUSER = URL+"/api/oders-product"
export const DELETECARTUSER = URL+"api/delete-cart-product"
export const UPDATECARTUSER = URL+"api/update-cart-product"
export const ORDERCARTUSER = URL+"api/orders-cart-product"
export const GET_ALL_USER_ORDERS = URL+"api/lich-su-cart-product"
export const HUY_USER_ORDERS = URL+"api/huy-don-cart-product"
export const CHI_TIET_ORDERS = URL+"api/chi-tiet-don-cart-product"
export const DELETE_ORDERS = URL+"api/delete-orders"
export const GET_ALL_NEWS = URL+"api/get-all-news"
export const GET_ONE_MEMBER = URL+"get/one-member"
export const GET_DANH_SACH_SAN_PHAM_MEMBER = URL+"api/get-all-catygory-product"
export const DELETE_TIEN_DA_NAP = URL+"api/delete-nap-tien-Member"